name: Auto EUserv

on:
  schedule:
    - cron: '30 3 6,7,8 * *'  # 每月6到8号 UTC 时间 凌晨3:30 运行，连续3天自动续期
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'  # 指定Python3.x

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
        EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
        EUSERV_2FA_SECRET: ${{ secrets.EUSERV_2FA_SECRET }}
        TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
        TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
      run: python Github_Action.py
